# Generated by Django 3.1 on 2023-01-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewYearPainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('keywords', models.CharField(max_length=100)),
            ],
        ),
    ]
